//! Phase 17 Wave 3.1 — hardware attestation scaffold.
//!
//! # What this is
//!
//! A pluggable API for hardware-backed attestation of a Tirami node.
//! When a peer can prove (to the quality level their hardware
//! supports) that it's running on a trusted enclave — Apple Secure
//! Enclave, NVIDIA H100 confidential-compute mode, Intel SGX —
//! other nodes grant it:
//!
//! * A priority bit on its [`tirami_core::PriceSignal`]
//!   (`attested: bool = true`).
//! * Faster `AuditTier` promotion (5× the usual rate).
//! * Optional routing preference (operators opt in via config).
//!
//! # What this is NOT
//!
//! Attestation is explicitly **optional premium**. Phase 17 does not
//! require it for any node to participate — the distributed-ethos
//! goal is that a Raspberry Pi can still serve. Attestation is a
//! differentiator for peers who want to earn more, not a gate on
//! participation.
//!
//! # Status
//!
//! Scaffold only in this wave:
//!
//! * [`AttestationProvider`] trait — pluggable producer.
//! * [`AttestationVerifier`] trait — pluggable consumer.
//! * [`AttestationReport`] — wire format.
//! * [`MockAttestationProvider`] / [`MockAttestationVerifier`] —
//!   deterministic pair for tests.
//!
//! Real hardware bindings are deferred:
//!
//! * **Apple Secure Enclave**: the `security-framework` crate binds
//!   the Keychain and SE APIs. Integration will land once we have
//!   an operator testbed on Apple Silicon.
//! * **NVIDIA H100 Confidential Compute**: `nvml-wrapper` exposes
//!   the CC mode bit. The attestation payload is a signed CC report
//!   from the driver.
//! * **Intel SGX / TDX**: via DCAP quoting; Azure / GCP confidential
//!   VMs. Lower priority — most Tirami provider hardware is GPU.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tirami_core_self_ref::NodeId;

// Internal alias so the module can be moved later without touching
// every path.
mod tirami_core_self_ref {
    pub use crate::types::NodeId;
}

// ---------------------------------------------------------------------------
// AttestationKind
// ---------------------------------------------------------------------------

/// Which hardware backed the attestation. Serialized over the wire
/// so verifiers can pick the right [`AttestationVerifier`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AttestationKind {
    /// `MockAttestationProvider` — deterministic, for tests only.
    Mock,
    /// Apple Secure Enclave — iOS / macOS on Apple Silicon.
    AppleSecureEnclave,
    /// NVIDIA H100 Confidential Compute — dedicated GPU feature.
    NvidiaH100CC,
    /// Intel SGX / TDX (DCAP quote).
    IntelSgx,
    /// AMD SEV-SNP.
    AmdSevSnp,
}

impl AttestationKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Mock => "mock",
            Self::AppleSecureEnclave => "apple-se",
            Self::NvidiaH100CC => "nvidia-h100-cc",
            Self::IntelSgx => "intel-sgx",
            Self::AmdSevSnp => "amd-sev-snp",
        }
    }

    /// True iff this kind is production-grade (not the mock).
    pub fn is_production(&self) -> bool {
        !matches!(self, Self::Mock)
    }
}

// ---------------------------------------------------------------------------
// AttestationReport — wire format
// ---------------------------------------------------------------------------

/// Self-contained attestation claim. Gossiped alongside `PriceSignal`
/// so any peer can verify without out-of-band communication.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestationReport {
    pub kind: AttestationKind,
    /// Node the attestation is bound to. A verifier MUST reject any
    /// report whose `node_id` does not match the claimed peer.
    pub node_id: NodeId,
    /// Hardware-scheme-specific attestation bytes. For the mock this
    /// is a SHA-256 of `node_id || issued_at_ms`.
    pub evidence: Vec<u8>,
    /// Unix ms when the report was generated by the provider.
    pub issued_at_ms: u64,
    /// Unix ms after which the report is stale. Verifiers reject
    /// reports older than this.
    pub valid_until_ms: u64,
}

impl AttestationReport {
    /// True iff `now_ms` is within the report's validity window.
    pub fn is_current(&self, now_ms: u64) -> bool {
        now_ms >= self.issued_at_ms && now_ms <= self.valid_until_ms
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum AttestationError {
    #[error("attestation kind mismatch: report={report:?}, verifier expects {expected:?}")]
    KindMismatch {
        report: AttestationKind,
        expected: AttestationKind,
    },
    #[error("attestation is stale: now_ms={now_ms}, valid_until={valid_until_ms}")]
    Stale {
        now_ms: u64,
        valid_until_ms: u64,
    },
    #[error("attestation node_id mismatch: report={report}, peer={peer}")]
    NodeIdMismatch { report: String, peer: String },
    #[error("attestation evidence failed cryptographic verification")]
    InvalidEvidence,
}

// ---------------------------------------------------------------------------
// Traits
// ---------------------------------------------------------------------------

/// Produces attestation reports. Backed by specific hardware in
/// real implementations; the mock hashes inputs.
pub trait AttestationProvider: Send + Sync {
    fn kind(&self) -> AttestationKind;
    /// Produce a fresh report for the given node at `now_ms`.
    /// `validity_ms` is how long the report should remain valid.
    fn attest(&self, node_id: NodeId, now_ms: u64, validity_ms: u64) -> AttestationReport;
}

/// Verifies attestation reports. Stateless from the API shape; real
/// implementations may cache trust-roots internally.
pub trait AttestationVerifier: Send + Sync {
    fn kind(&self) -> AttestationKind;
    /// Verify that `report` was produced by a legitimate attestation
    /// chain for `expected_peer` at `now_ms`.
    fn verify(
        &self,
        report: &AttestationReport,
        expected_peer: &NodeId,
        now_ms: u64,
    ) -> Result<(), AttestationError>;
}

// ---------------------------------------------------------------------------
// MockAttestationProvider / Verifier
// ---------------------------------------------------------------------------

/// Deterministic provider. Evidence = SHA-256("tirami-mock-attest" ||
/// node_id.0 || issued_at_ms.to_le_bytes()).
#[derive(Debug, Clone, Copy, Default)]
pub struct MockAttestationProvider;

impl MockAttestationProvider {
    const SALT: &'static [u8] = b"tirami-mock-attest";
}

impl AttestationProvider for MockAttestationProvider {
    fn kind(&self) -> AttestationKind {
        AttestationKind::Mock
    }

    fn attest(
        &self,
        node_id: NodeId,
        now_ms: u64,
        validity_ms: u64,
    ) -> AttestationReport {
        let mut h = Sha256::new();
        h.update(Self::SALT);
        h.update(node_id.0);
        h.update(now_ms.to_le_bytes());
        let evidence = h.finalize().to_vec();
        AttestationReport {
            kind: AttestationKind::Mock,
            node_id,
            evidence,
            issued_at_ms: now_ms,
            valid_until_ms: now_ms.saturating_add(validity_ms),
        }
    }
}

/// Matching verifier for [`MockAttestationProvider`]. Re-derives the
/// expected hash and compares byte-wise.
#[derive(Debug, Clone, Copy, Default)]
pub struct MockAttestationVerifier;

impl AttestationVerifier for MockAttestationVerifier {
    fn kind(&self) -> AttestationKind {
        AttestationKind::Mock
    }

    fn verify(
        &self,
        report: &AttestationReport,
        expected_peer: &NodeId,
        now_ms: u64,
    ) -> Result<(), AttestationError> {
        if report.kind != AttestationKind::Mock {
            return Err(AttestationError::KindMismatch {
                report: report.kind,
                expected: AttestationKind::Mock,
            });
        }
        if report.node_id != *expected_peer {
            return Err(AttestationError::NodeIdMismatch {
                report: report.node_id.to_hex(),
                peer: expected_peer.to_hex(),
            });
        }
        if !report.is_current(now_ms) {
            return Err(AttestationError::Stale {
                now_ms,
                valid_until_ms: report.valid_until_ms,
            });
        }
        let mut h = Sha256::new();
        h.update(MockAttestationProvider::SALT);
        h.update(report.node_id.0);
        h.update(report.issued_at_ms.to_le_bytes());
        let expected = h.finalize();
        // Constant-time byte compare.
        if report.evidence.len() != 32 {
            return Err(AttestationError::InvalidEvidence);
        }
        let mut diff: u8 = 0;
        for (a, b) in expected.iter().zip(report.evidence.iter()) {
            diff |= a ^ b;
        }
        if diff != 0 {
            return Err(AttestationError::InvalidEvidence);
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Routing hints
// ---------------------------------------------------------------------------

/// How much faster an attested peer should climb the `AuditTier`
/// ladder, per the Phase 17 Wave 3.1 spec.
pub const ATTESTED_AUDIT_TIER_SPEED_MULTIPLIER: u32 = 5;

/// Whether a newly-received `PriceSignal` from a known-attested
/// peer should be routing-preferred over non-attested equivalents.
/// Operators opt in via `Config::prefer_attested_providers`
/// (wire-up in Wave-3.1-part-2 once the trait surface is wired
/// into `PeerRegistry`).
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct AttestationPreferences {
    pub prefer_attested_providers: bool,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn nid(b: u8) -> NodeId {
        NodeId([b; 32])
    }

    #[test]
    fn kind_as_str_roundtrips() {
        assert_eq!(AttestationKind::Mock.as_str(), "mock");
        assert_eq!(AttestationKind::AppleSecureEnclave.as_str(), "apple-se");
        assert_eq!(AttestationKind::NvidiaH100CC.as_str(), "nvidia-h100-cc");
        assert_eq!(AttestationKind::IntelSgx.as_str(), "intel-sgx");
        assert_eq!(AttestationKind::AmdSevSnp.as_str(), "amd-sev-snp");
    }

    #[test]
    fn kind_is_production_excludes_mock() {
        assert!(!AttestationKind::Mock.is_production());
        assert!(AttestationKind::AppleSecureEnclave.is_production());
        assert!(AttestationKind::NvidiaH100CC.is_production());
    }

    #[test]
    fn mock_attest_round_trips_through_verify() {
        let p = MockAttestationProvider;
        let v = MockAttestationVerifier;
        let rep = p.attest(nid(1), 1_000, 60_000);
        assert!(v.verify(&rep, &nid(1), 1_500).is_ok());
    }

    #[test]
    fn verify_rejects_wrong_peer() {
        let p = MockAttestationProvider;
        let v = MockAttestationVerifier;
        let rep = p.attest(nid(1), 1_000, 60_000);
        let err = v.verify(&rep, &nid(2), 1_500).unwrap_err();
        assert!(matches!(err, AttestationError::NodeIdMismatch { .. }));
    }

    #[test]
    fn verify_rejects_stale_report() {
        let p = MockAttestationProvider;
        let v = MockAttestationVerifier;
        let rep = p.attest(nid(1), 1_000, 60_000); // valid until 61 000
        let err = v.verify(&rep, &nid(1), 100_000).unwrap_err();
        assert!(matches!(err, AttestationError::Stale { .. }));
    }

    #[test]
    fn verify_rejects_pre_issuance() {
        let p = MockAttestationProvider;
        let v = MockAttestationVerifier;
        let rep = p.attest(nid(1), 10_000, 60_000);
        // Verifier's clock is behind the issuer's — treat as stale.
        let err = v.verify(&rep, &nid(1), 5_000).unwrap_err();
        assert!(matches!(err, AttestationError::Stale { .. }));
    }

    #[test]
    fn verify_rejects_kind_mismatch() {
        let v = MockAttestationVerifier;
        let mut rep = MockAttestationProvider.attest(nid(1), 1_000, 60_000);
        rep.kind = AttestationKind::NvidiaH100CC;
        let err = v.verify(&rep, &nid(1), 1_500).unwrap_err();
        assert!(matches!(err, AttestationError::KindMismatch { .. }));
    }

    #[test]
    fn verify_rejects_tampered_evidence() {
        let v = MockAttestationVerifier;
        let mut rep = MockAttestationProvider.attest(nid(1), 1_000, 60_000);
        rep.evidence[0] ^= 0xFF;
        let err = v.verify(&rep, &nid(1), 1_500).unwrap_err();
        assert_eq!(err, AttestationError::InvalidEvidence);
    }

    #[test]
    fn verify_rejects_wrong_length_evidence() {
        let v = MockAttestationVerifier;
        let mut rep = MockAttestationProvider.attest(nid(1), 1_000, 60_000);
        rep.evidence.truncate(10);
        let err = v.verify(&rep, &nid(1), 1_500).unwrap_err();
        assert_eq!(err, AttestationError::InvalidEvidence);
    }

    #[test]
    fn report_is_current_reflects_bounds() {
        let p = MockAttestationProvider;
        let rep = p.attest(nid(1), 1_000, 5_000);
        assert!(rep.is_current(1_000)); // lower bound inclusive
        assert!(rep.is_current(6_000)); // upper bound inclusive
        assert!(!rep.is_current(999));
        assert!(!rep.is_current(6_001));
    }

    #[test]
    fn serde_roundtrips_report() {
        let rep = MockAttestationProvider.attest(nid(1), 1_000, 60_000);
        let s = serde_json::to_string(&rep).unwrap();
        let back: AttestationReport = serde_json::from_str(&s).unwrap();
        assert_eq!(back, rep);
    }

    #[test]
    fn audit_tier_multiplier_is_five() {
        // Constant guard — if someone changes the multiplier, a test
        // must alert before the economic balance shifts silently.
        assert_eq!(ATTESTED_AUDIT_TIER_SPEED_MULTIPLIER, 5);
    }

    #[test]
    fn preferences_default_is_off() {
        let p = AttestationPreferences::default();
        assert!(!p.prefer_attested_providers);
    }

    #[test]
    fn provider_kind_matches_report_kind() {
        // The kind the provider advertises MUST match the report it
        // produces — otherwise a verifier can't route to the right
        // verifier implementation.
        let p = MockAttestationProvider;
        let rep = p.attest(nid(1), 1_000, 60_000);
        assert_eq!(p.kind(), rep.kind);
    }
}
