//! Phase 17 Wave 3.5 — key rotation scaffold for node identities.
//!
//! # Problem
//!
//! Pre-Phase-17 Tirami uses a single long-lived Ed25519 keypair per
//! node, generated on first launch and stored in the platform
//! keychain. If that key is compromised, the only recovery is to
//! spin up a new node with a fresh identity — losing all accrued
//! reputation, stake, and lending history. That's operationally
//! painful and makes rotation discipline nonexistent.
//!
//! # Solution
//!
//! A [`NodeIdentity`] owns a short `Vec<KeyEpoch>`:
//!
//! * At any time exactly one epoch has [`KeyState::Active`]; that key
//!   signs all new outbound trades / loans / gossip.
//! * Old epochs retain [`KeyState::Revoked`] state. Historical
//!   signatures produced BEFORE the revocation timestamp remain
//!   verifiable; any NEW signature received under a revoked key is
//!   rejected.
//! * Rotation is an explicit operator action — `NodeIdentity::rotate`
//!   generates a new keypair, flips the old one to Revoked, marks
//!   the new one Active. The CLI gesture is `forge node rotate-key`.
//!
//! # Status in this wave
//!
//! This module delivers the type lattice + verify logic + full test
//! matrix. The production integration (migrate `ForgeTransport` to
//! consume `NodeIdentity` instead of a bare `SigningKey`, add the
//! CLI entrypoint, persist the epoch history to disk) is
//! Wave-3.5-part-2. The scaffold is a drop-in when that lands.

use ed25519_dalek::{Signer, SigningKey, Verifier, VerifyingKey};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};

/// State of a single key epoch within a [`NodeIdentity`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyState {
    /// The currently-signing key. Exactly one per identity.
    Active,
    /// Previously Active; new signatures with this key must be
    /// rejected, but signatures produced while it was Active are
    /// retained as valid history.
    Revoked,
}

/// One key epoch in a node's identity lifecycle.
///
/// Serializable so the whole history can be snapshot to the
/// keychain-backed store alongside existing node state.
#[derive(Clone, Serialize, Deserialize)]
pub struct KeyEpoch {
    /// Monotonic epoch id starting at 0. Included in signature
    /// contexts so a verifier can look up which public key applies.
    pub epoch: u32,
    /// Raw seed bytes of the signing key. Kept opaque outside this
    /// module — callers never touch them directly.
    signing_seed: [u8; 32],
    /// 32-byte Ed25519 verification key (public component).
    pub verifying_key_bytes: [u8; 32],
    pub state: KeyState,
    /// Unix ms when the epoch was created (i.e. key generated).
    pub created_at_ms: u64,
    /// Unix ms when the epoch was revoked; `None` while Active.
    pub revoked_at_ms: Option<u64>,
}

impl std::fmt::Debug for KeyEpoch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("KeyEpoch")
            .field("epoch", &self.epoch)
            .field("verifying_key_hex", &hex::encode(self.verifying_key_bytes))
            .field("state", &self.state)
            .field("created_at_ms", &self.created_at_ms)
            .field("revoked_at_ms", &self.revoked_at_ms)
            .finish()
    }
}

impl KeyEpoch {
    /// Reconstruct the `SigningKey` from the stored seed. The
    /// returned value is NOT cached — callers should not hold onto
    /// it long because that extends the in-memory window the seed
    /// is exposed.
    pub fn signing_key(&self) -> SigningKey {
        SigningKey::from_bytes(&self.signing_seed)
    }

    /// `VerifyingKey` for this epoch. Infallible because we
    /// generated the bytes ourselves at construction.
    pub fn verifying_key(&self) -> VerifyingKey {
        VerifyingKey::from_bytes(&self.verifying_key_bytes)
            .expect("verifying key bytes were generated by us")
    }
}

// ---------------------------------------------------------------------------
// NodeIdentity
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, thiserror::Error)]
pub enum KeyRotationError {
    #[error("no active key epoch — identity is in an inconsistent state")]
    NoActiveKey,
    #[error("more than one Active epoch — internal consistency bug")]
    MultipleActiveKeys,
    #[error("signature does not verify under any known epoch")]
    UnknownSigningKey,
    #[error("signature verifies but key was revoked before signing_at_ms={signing_at_ms} \
             (revoked at {revoked_at_ms})")]
    RevokedKeyUsed {
        signing_at_ms: u64,
        revoked_at_ms: u64,
    },
}

/// A node's full key history. Exactly one epoch is Active at any
/// time. Old epochs stay in the vector for historical verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeIdentity {
    epochs: Vec<KeyEpoch>,
}

impl Default for NodeIdentity {
    fn default() -> Self {
        Self::new()
    }
}

impl NodeIdentity {
    /// Bootstrap a fresh identity with a single Active epoch.
    pub fn new() -> Self {
        Self::with_clock(now_ms())
    }

    /// Testing-friendly constructor that accepts an explicit
    /// creation timestamp.
    pub fn with_clock(now_ms: u64) -> Self {
        let mut rng = OsRng;
        let signing = SigningKey::generate(&mut rng);
        let vk = signing.verifying_key().to_bytes();
        let epoch = KeyEpoch {
            epoch: 0,
            signing_seed: signing.to_bytes(),
            verifying_key_bytes: vk,
            state: KeyState::Active,
            created_at_ms: now_ms,
            revoked_at_ms: None,
        };
        Self {
            epochs: vec![epoch],
        }
    }

    /// Currently-active epoch. Returns an error if internal state
    /// is inconsistent (should not happen in practice).
    pub fn active(&self) -> Result<&KeyEpoch, KeyRotationError> {
        let actives: Vec<&KeyEpoch> = self
            .epochs
            .iter()
            .filter(|e| e.state == KeyState::Active)
            .collect();
        match actives.len() {
            0 => Err(KeyRotationError::NoActiveKey),
            1 => Ok(actives[0]),
            _ => Err(KeyRotationError::MultipleActiveKeys),
        }
    }

    /// Rotate: mark the current Active epoch as Revoked, generate a
    /// fresh keypair as the new Active epoch. Returns the new epoch.
    ///
    /// Fails if the identity is already in an inconsistent state
    /// (zero or multiple Actives).
    pub fn rotate(&mut self, now_ms: u64) -> Result<&KeyEpoch, KeyRotationError> {
        let active_epoch_id = self.active()?.epoch;
        for e in self.epochs.iter_mut() {
            if e.epoch == active_epoch_id {
                e.state = KeyState::Revoked;
                e.revoked_at_ms = Some(now_ms);
            }
        }
        let next_id = self.epochs.iter().map(|e| e.epoch).max().unwrap_or(0) + 1;
        let mut rng = OsRng;
        let signing = SigningKey::generate(&mut rng);
        let vk = signing.verifying_key().to_bytes();
        self.epochs.push(KeyEpoch {
            epoch: next_id,
            signing_seed: signing.to_bytes(),
            verifying_key_bytes: vk,
            state: KeyState::Active,
            created_at_ms: now_ms,
            revoked_at_ms: None,
        });
        Ok(self.epochs.last().expect("just pushed"))
    }

    /// Sign `msg` with the currently-active epoch's key.
    pub fn sign(&self, msg: &[u8]) -> Result<Vec<u8>, KeyRotationError> {
        let active = self.active()?;
        let sig = active.signing_key().sign(msg);
        Ok(sig.to_bytes().to_vec())
    }

    /// Iterate every epoch this identity has ever had. Order is by
    /// epoch id ascending.
    pub fn epochs(&self) -> impl Iterator<Item = &KeyEpoch> {
        self.epochs.iter()
    }

    pub fn epoch_count(&self) -> usize {
        self.epochs.len()
    }
}

// ---------------------------------------------------------------------------
// Verify helper (history-aware)
// ---------------------------------------------------------------------------

/// Verify that `sig_bytes` is a valid Ed25519 signature over `msg`
/// by ANY epoch in `identity`, AND that the signing epoch was
/// Active at `signing_at_ms` (i.e. either still Active, or revoked
/// strictly after the signing timestamp).
///
/// Returns the epoch id that verified on success.
pub fn verify_historical(
    identity: &NodeIdentity,
    msg: &[u8],
    sig_bytes: &[u8],
    signing_at_ms: u64,
) -> Result<u32, KeyRotationError> {
    let sig_arr: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| KeyRotationError::UnknownSigningKey)?;
    let sig = ed25519_dalek::Signature::from_bytes(&sig_arr);
    for e in identity.epochs() {
        if e.verifying_key().verify(msg, &sig).is_ok() {
            return match e.state {
                KeyState::Active => Ok(e.epoch),
                KeyState::Revoked => {
                    if let Some(revoked_at) = e.revoked_at_ms {
                        if signing_at_ms <= revoked_at {
                            Ok(e.epoch)
                        } else {
                            Err(KeyRotationError::RevokedKeyUsed {
                                signing_at_ms,
                                revoked_at_ms: revoked_at,
                            })
                        }
                    } else {
                        // Revoked without a timestamp — treat as if
                        // revoked at epoch time 0, so any signing
                        // after that is rejected.
                        Err(KeyRotationError::RevokedKeyUsed {
                            signing_at_ms,
                            revoked_at_ms: 0,
                        })
                    }
                }
            };
        }
    }
    Err(KeyRotationError::UnknownSigningKey)
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fresh_identity_has_single_active_epoch() {
        let id = NodeIdentity::with_clock(1_000);
        assert_eq!(id.epoch_count(), 1);
        let active = id.active().unwrap();
        assert_eq!(active.epoch, 0);
        assert_eq!(active.state, KeyState::Active);
        assert_eq!(active.created_at_ms, 1_000);
        assert!(active.revoked_at_ms.is_none());
    }

    #[test]
    fn sign_uses_active_key() {
        let id = NodeIdentity::with_clock(1_000);
        let sig = id.sign(b"hello").unwrap();
        assert_eq!(sig.len(), 64);
        // Verify round-trip against the active epoch's VK.
        let active_vk = id.active().unwrap().verifying_key();
        let sig_arr: [u8; 64] = sig.try_into().unwrap();
        assert!(active_vk
            .verify(b"hello", &ed25519_dalek::Signature::from_bytes(&sig_arr))
            .is_ok());
    }

    #[test]
    fn rotate_moves_current_active_to_revoked_and_creates_fresh_active() {
        let mut id = NodeIdentity::with_clock(1_000);
        let _old_vk = id.active().unwrap().verifying_key_bytes;
        id.rotate(2_000).unwrap();
        assert_eq!(id.epoch_count(), 2);
        // Epoch 0 must be Revoked at 2_000.
        let old = id.epochs().find(|e| e.epoch == 0).unwrap();
        assert_eq!(old.state, KeyState::Revoked);
        assert_eq!(old.revoked_at_ms, Some(2_000));
        // Epoch 1 must be the new Active.
        let new = id.active().unwrap();
        assert_eq!(new.epoch, 1);
        assert_eq!(new.state, KeyState::Active);
        assert_eq!(new.created_at_ms, 2_000);
    }

    #[test]
    fn rotate_generates_distinct_keypair() {
        let mut id = NodeIdentity::with_clock(1_000);
        let old_vk = id.active().unwrap().verifying_key_bytes;
        id.rotate(2_000).unwrap();
        let new_vk = id.active().unwrap().verifying_key_bytes;
        assert_ne!(old_vk, new_vk);
    }

    #[test]
    fn historical_signature_by_revoked_key_is_still_accepted() {
        // Sign at t=500 with epoch 0. Rotate at t=2000. A verifier
        // checking at t=1500 (between sign and rotate) must accept.
        let mut id = NodeIdentity::with_clock(1_000);
        let sig = id.sign(b"past").unwrap();
        id.rotate(2_000).unwrap();
        let ok = verify_historical(&id, b"past", &sig, 1_500).unwrap();
        assert_eq!(ok, 0); // epoch 0's key verified
    }

    #[test]
    fn new_signature_by_revoked_key_is_rejected() {
        let mut id = NodeIdentity::with_clock(1_000);
        // Save the old epoch's signing key BEFORE rotation.
        let old_sig = id.sign(b"future").unwrap();
        id.rotate(2_000).unwrap();
        // Pretend the old-key signature was produced at 3_000 —
        // AFTER the key was revoked. Must reject.
        let err = verify_historical(&id, b"future", &old_sig, 3_000).unwrap_err();
        assert!(matches!(err, KeyRotationError::RevokedKeyUsed { .. }));
    }

    #[test]
    fn new_signature_by_currently_active_key_is_accepted_at_any_time() {
        let mut id = NodeIdentity::with_clock(1_000);
        id.rotate(2_000).unwrap();
        let sig = id.sign(b"now").unwrap();
        // Any t >= current epoch creation is fine.
        let ok = verify_historical(&id, b"now", &sig, 3_000).unwrap();
        assert_eq!(ok, 1);
    }

    #[test]
    fn verify_rejects_malformed_signature_length() {
        let id = NodeIdentity::with_clock(1_000);
        let err = verify_historical(&id, b"m", &[0u8; 10], 1_000).unwrap_err();
        assert!(matches!(err, KeyRotationError::UnknownSigningKey));
    }

    #[test]
    fn verify_rejects_signature_from_foreign_key() {
        let id = NodeIdentity::with_clock(1_000);
        let mut rng = OsRng;
        let foreign = SigningKey::generate(&mut rng);
        let sig = foreign.sign(b"msg");
        let err = verify_historical(&id, b"msg", &sig.to_bytes(), 1_500).unwrap_err();
        assert!(matches!(err, KeyRotationError::UnknownSigningKey));
    }

    #[test]
    fn multiple_rotations_accumulate_history() {
        let mut id = NodeIdentity::with_clock(1_000);
        let sig_0 = id.sign(b"v0").unwrap();
        id.rotate(2_000).unwrap();
        let sig_1 = id.sign(b"v1").unwrap();
        id.rotate(3_000).unwrap();
        let sig_2 = id.sign(b"v2").unwrap();
        assert_eq!(id.epoch_count(), 3);
        // Each historical signature must verify via its own epoch,
        // scoped to the right time.
        assert_eq!(verify_historical(&id, b"v0", &sig_0, 1_500).unwrap(), 0);
        assert_eq!(verify_historical(&id, b"v1", &sig_1, 2_500).unwrap(), 1);
        assert_eq!(verify_historical(&id, b"v2", &sig_2, 3_500).unwrap(), 2);
    }

    #[test]
    fn rotate_twice_correctly_marks_only_the_most_recent_active() {
        let mut id = NodeIdentity::with_clock(1_000);
        id.rotate(2_000).unwrap();
        id.rotate(3_000).unwrap();
        let actives: Vec<_> = id
            .epochs()
            .filter(|e| e.state == KeyState::Active)
            .collect();
        assert_eq!(actives.len(), 1);
        assert_eq!(actives[0].epoch, 2);
    }

    #[test]
    fn serde_roundtrips_identity_including_revoked_epochs() {
        let mut id = NodeIdentity::with_clock(1_000);
        id.rotate(2_000).unwrap();
        let s = serde_json::to_string(&id).unwrap();
        let back: NodeIdentity = serde_json::from_str(&s).unwrap();
        assert_eq!(back.epoch_count(), 2);
        let back_active = back.active().unwrap();
        assert_eq!(back_active.epoch, 1);
        // Revoked epoch survives round-trip with its timestamp.
        let back_old = back.epochs().find(|e| e.epoch == 0).unwrap();
        assert_eq!(back_old.state, KeyState::Revoked);
        assert_eq!(back_old.revoked_at_ms, Some(2_000));
    }
}
